name: Terraform CI/CD

on: [push, pull_request]

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Init
        run: terraform init

      - name: Validate
        id: validate
        run: terraform validate
        continue-on-error: true

      - name: Display Validation Result
        if: always()
        run: |
          echo "## Validation Result"
          if [[ "${{ steps.validate.outcome }}" == "success" ]]; then
            echo "✅ Validation succeeded!"
          else
            echo "❌ Validation failed!"
          fi

      - name: Setup SSH Key
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
          ssh-passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          TF_VAR_vps_ssh_key: ${{ secrets.VPS_SSH_KEY }}

