name: Terraform CI/CD

on: [push, pull_request]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: SSH Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          private_key: ${{ secrets.VPS_SSH_KEY }}
          scp_source: './'
          scp_target: '/root/tf-infra/'
          before_script: |
            whoami
          after_script: |
            cd /root/tf-infra 
            terraform init
            terraform apply -auto-approve

