name: Terraform Lint

on: [push, pull_request]

jobs:
  terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        id: init
        uses: hashicorp/setup-terraform@v3.1.1
      
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Plan deployment
        id: plan
        run: terraform plan -no-color
