name: Terraform Lint

on: [push, pull_request]

jobs:
  terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        id: init
        uses: hashicorp/setup-terraform@v3.1.1
      
      - name: Init
        run: terraform init
      - name: Validate
        id: validate
        run: terraform validate
       - name: Add Validation Result to Job Summary
        if: always()
        run: |
          if [[ "${{ steps.validate.outcome }}" == "success" ]]; then
            echo "## Validation Result" >> $GITHUB_STEP_SUMMARY
            echo "✅ Validation succeeded!" >> $GITHUB_STEP_SUMMARY
          else
            echo "## Validation Result" >> $GITHUB_STEP_SUMMARY
            echo "❌ Validation failed!" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat validate_output.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Plan deployment
        id: plan
        run: terraform plan -no-color
