name: Terraform Lint

on: [push, pull_request]

jobs:
  terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        id: init
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Init
        run: terraform init

      - name: Validate
        id: validate
        run: |
          terraform validate > validate_output.txt
          cat validate_output.txt
          echo "::set-output name=result::$(cat validate_output.txt)"
        continue-on-error: true

      - name: Display Validation Result
        if: always()
        run: |
          if [[ "${{ steps.validate.outcome }}" == "success" ]]; then
            echo "✅ Validation succeeded!"
          else
            echo "❌ Validation failed!"
            cat validate_output.txt
          fi

      - name: Add Validation Result to Job Summary
        if: always()
        run: |
          if [[ "${{ steps.validate.outcome }}" == "success" ]]; then
            echo "## Validation Result" >> $GITHUB_STEP_SUMMARY
            echo "✅ Validation succeeded!" >> $GITHUB_STEP_SUMMARY
          else
            echo "## Validation Result" >> $GITHUB_STEP_SUMMARY
            echo "❌ Validation failed!" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat validate_output.txt >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Annotate Validation Result
        if: always()
        run: |
          if [[ "${{ steps.validate.outcome }}" == "success" ]]; then
            echo "✅ Validation succeeded!"
          else
            echo "❌ Validation failed!"
            while IFS= read -r line; do
              echo "::error file=terraform.tf::${line}"
            done < validate_output.txt

      - name: Upload Validation Output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: validation-output
          path: validate_output.txt

